baseURL = "https://builtbynikhil.com/"
languageCode = "en-us"
title = "Built by Nikhil"
theme = "blowfish"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  description = "Articles, notes, and ideas on technology, management, and more."
  mainSections = ["tech", "management", "arduino", "quotes", "brain"]

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true